### PR TITLE
Update sample data and fix top-up non-existent category bug

### LINKED ISSUE #103: [PE-D] Cannot topup
The topup command woun't give any response when I do topup command.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Raymond0212/ped#3

### LINKED ISSUE #105: [PE-D] The tag cannot be added without date.
In the UG of add command, it says that tag and date are all optional. But in testing,  I find that without date, the tag cannot be set as what I input. It will be always set as default.

Note: I find the reason is that the category does not exsit when first launching the app although it is shown in the screen. This will make user feel confused and then cause many commands to fail, such as edit, deleteCat.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: XIA-LIYI/ped#1

### LINKED ISSUE #107: [PE-D] Fail to edit category.
As attached, this edit command should be valid. But when I run it, I find it does not work. At the same time, no feedback is given to me. It is stuck there.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: XIA-LIYI/ped#3

### LINKED ISSUE #109: [PE-D] Add category will cause wrong balance
After adding a new category, it will cause balance to be negative.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: XIA-LIYI/ped#5

### LINKED ISSUE #110: [PE-D] Topup cannot work well
Since the bug caused by adding category, the topup command will fail as a consequence.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: XIA-LIYI/ped#6

### LINKED ISSUE #120: [PE-D] Putting multiple commands in one line results in unexpected behaviour
Given the initial state (with the `Food` tag present), I encounter

This is given the command `add -d dinner -$10.50, add -d dinner -$10.50 -@20-08-2020 t/Food`. The error message does not correspond to the error, saying that `Tags: Default' does not exist yet -- tagging as 'Default' instead`. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: theodoreleebrant/ped#9

### LINKED ISSUE #123: [PE-D] Uncaught exception (app freezes) given topup a category that does not exist
Step to reproduce: `topup -$30 t/Food` without the category `Food` being made.  
Putting this as Medium because there is no error or any indication of anything happening (which I happen to know that it causes uncaught exception)

The following image stays like thatt even after I pressed enter.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: theodoreleebrant/ped#12

### LINKED ISSUE #127: [PE-D] Tags (or Categories, ambiguous in the UG and App) are not present with the sample data
I can add the category (or tag) `Food` even though it is clearly in the sample data.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: theodoreleebrant/ped#16

### LINKED ISSUE #128: [PE-D] Command result does not display what user input as a tag when invalid
Adding a new item with a tag that has not been initialized results in it being shown as default in the help text. Really minor problem - but would be useful to see what has been typed in so as to know its a typo (for eg.)
Reproducable by adding a new item with a tag that is not in the system yet e.g. t/abcdef

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: WangZijun97/ped#1

### LINKED ISSUE #129: [PE-D] Unable to edit tags
Edit command unable to be submitted when there is a tag in it. Pressing 'enter' key does not appear to do anything here. Might be related to the issue on "Default" tags as t/Default works.

**Edit**: Upon further testing I think the tags that exist in the default data do not exist in the App on startup.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: WangZijun97/ped#2

### LINKED ISSUE #134: [PE-D] Bug when adding expense with tag
Steps to reproduce bug: Launch application and enter the above command.

Unable to add an expense with tag 'Food' even though there already exists expenses in the list with tag 'Food'.
The error message also does not seem to clearly explain what is happening. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: timjkong/ped#1

### LINKED ISSUE #136: [PE-D] Add Category Bug
Successfully added category 'Food' even though the category already exists.

Additionally, the budget balance bar looks like this after entering the command:

The budget balance feature no longer works after encountering this bug. Refer to issue 5 for an example.

Steps to reproduce bug: Launch application and enter the command addCat t/Food

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: timjkong/ped#3

### LINKED ISSUE #137: [PE-D] Delete Category Bug
Unable to delete category 'Girlfriend' even though it already exists. 
Additionally, there is a grammatical error in the error message. Perhaps it should be 'This category does not exist in the expense book' instead.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: timjkong/ped#4

### LINKED ISSUE #138: [PE-D] Topup feature bug following issue #3
After entering the above command, budget balance can no longer be topped up, and the budget balance bar remains as shown:

Steps to reproduce bug: Follow steps provided in issue #3 then enter a topup command.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: timjkong/ped#5

### LINKED ISSUE #139: [PE-D] Switch category bug
Unable to switch to category 'Shopping' even though it already exists.

Steps to reproduce bug: Launch application and enter the above command

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: timjkong/ped#6

### PR DESCRIPTION
**Pull request by lebencwb**
Fixes #103, fixes #105, fixes #107, fixes #109, fixes #110, fixes #120, fixes #123, fixes #127, fixes #128, fixes #129, fixes #134, fixes #136, fixes #137, fixes #138, fixes #139 (bugs due to incorrect sample data, and issues with the error message not displaying correctly when adding an expense with a non-existent category).

### CODE REVIEW

**Comment by maxxyh** [comment]
Doesn't seem to fix #108? Need to add a new exception for edit if no changes are requested.

File: src/main/java/seedu/expense/logic/commands/TopupCommand.java [hunk 1]
```diff
@@ -27,6 +28,7 @@
             + PREFIX_TAG + "Food";
 
     public static final String MESSAGE_SUCCESS = "New budget amount for %s: $%.02f";
+    public static final String MESSAGE_CATEGORY_NOT_FOUND = "The expense book does not contain the category %s";
```
Comment (maxxyh) [inline src/main/java/seedu/expense/logic/commands/TopupCommand.java:31]: I think the message could be more detailed: "The expense book does not contain the category %s. Please create it using the addCat command first."

**Comment by maxxyh** [comment]
Does this solve #127 ? Was #127 a result of the sample data?

**Comment by maxxyh** [comment]
#128 doesn't seem to be solved either - seems more like a UI problem - that the command should remain the command box?

File: src/main/java/seedu/expense/model/util/SampleDataUtil.java [hunk 2]
```diff
@@ -49,13 +51,19 @@
     }
 
     public static ReadOnlyExpenseBook getSampleExpenseBook() {
-        ExpenseBook sampleAb = new ExpenseBook();
+        ExpenseBook sampleEb = new ExpenseBook();
+
+        sampleEb.addCategory(new Tag("Girlfriend"));
+        sampleEb.addCategory(new Tag("Shopping"));
+        sampleEb.addCategory(new Tag("Food"));
+        sampleEb.addCategory(new Tag("Transport"));
```
Comment (maxxyh) [inline src/main/java/seedu/expense/model/util/SampleDataUtil.java]: I see where the issue is with this. Thank you Leben.

File: src/main/java/seedu/expense/model/util/SampleDataUtil.java [hunk 3]
```diff
@@ -49,13 +51,19 @@
...
 
-        sampleAb.topupBudget(new Amount(500));
+        sampleEb.getBudgets().topupBudget(new Amount("10"));
```
Comment (maxxyh) [inline src/main/java/seedu/expense/model/util/SampleDataUtil.java]: Can we increase the top-up amount to at least $200 to prevent -ve default data?

**Comment by maxxyh** [comment]
image

Will need to fix this part as well too. Instead of `return new CommandResult(String.format(MESSAGE_DEFAULT, expense))` it should be `return new CommandResult(String.format(MESSAGE_DEFAULT, <STORE AND GET THE ORIGINAL CATEGORY HERE>))`

File: src/main/java/seedu/expense/logic/commands/AddCommand.java [hunk 4]
```diff
@@ -55,7 +55,7 @@ public CommandResult execute(Model model) throws CommandException {
         if (!model.hasCategory(toAdd.getTag())) {
             Expense expense = toAdd.resetTag();
             model.addExpense(expense);
-            return new CommandResult(String.format(MESSAGE_DEFAULT, expense));
+            return new CommandResult(String.format(MESSAGE_DEFAULT, toAdd.getTag().tagName));
```
Comment (maxxyh) [inline src/main/java/seedu/expense/logic/commands/AddCommand.java:58]: Will this work even after the tag has been reset in line 56?

**Comment by maxxyh** [comment]
#138 doesn't seem to be addressed by the code changes

**Comment by maxxyh** [comment]
Also, error message in EditCommand needs to be updated. This could mean setting a default message for CategoryNotFoundException. 

This also means that this CategoryNotFoundException should be used in other situations such as AddCommand

image

File: src/main/java/seedu/expense/logic/commands/TopupCommand.java (hunk 1 above)
Comment (maxxyh) [reply src/main/java/seedu/expense/logic/commands/TopupCommand.java:31]: However, can we look into using `CategoryNotFoundException `for consistency?

File: src/main/java/seedu/expense/logic/commands/AddCommand.java (hunk 4 above)
Comment (lebencwb) [reply src/main/java/seedu/expense/logic/commands/AddCommand.java:58]: Yes, this works because `Expense` is immutable, and `Expense#resetTag` returns a new `Expense` object instead of modifying the original object.

**Comment by lebencwb** [comment]
> Doesn't seem to fix #108? Need to add a new exception for edit if no changes are requested.

Sorry, it was an oversight on my part. This PR does not fix #108 - I have updated the linked issues accordingly. Also, I have checked with the release again, and I did not encounter the bug raised. The error messages seem to be working as expected (screenshots appended below).

image

image

**Comment by lebencwb** [comment]
> Does this solve #127 ? Was #127 a result of the sample data?

Yes, #127 was due to the incorrect sample data, which did not contain any categories apart from the 'Default' category, but contained expenses tagged with those categories (a behavior that is prohibited in other parts of the code). This PR adds those missing categories in to the sample data.

**Comment by lebencwb** [comment]
> #128 doesn't seem to be solved either - seems more like a UI problem - that the command should remain the command box?

The original design was to alert the user to the fact that the tagged category did not exist yet, without throwing any exceptions. This PR patches the bug in which the message was not showing correctly.

This is the expected behaviour:
Input: `add -dExpense with new category -$1234.56 -@12-12-2020 t/abcdef`
Output:
image
image

**Comment by lebencwb** [comment]
> image
> 
> Will need to fix this part as well too. Instead of `return new CommandResult(String.format(MESSAGE_DEFAULT, expense))` it should be `return new CommandResult(String.format(MESSAGE_DEFAULT, <STORE AND GET THE ORIGINAL CATEGORY HERE>))`

Yes, thank you for catching that! It has been fixed by the changes in this PR.
`return new CommandResult(String.format(MESSAGE_DEFAULT, expense))` ->
`return new CommandResult(String.format(MESSAGE_DEFAULT, toAdd.getTag().tagName))`

**Comment by lebencwb** [comment]
> #138 doesn't seem to be addressed by the code changes

It seems to be caused by #136, which is due to the incorrect sample data. (See also: #109)

**Review by maxxyh — APPROVED** [review]
LGTM thank you Leben!
