### PR TITLE
Change Amount datatype to BigDecimal, Fix DescriptionComparator

### LINKED ISSUE #117: [PE-D] Functionality Bug: Money Overflow
Given a number that is too large, this would cause the amount of money owed to be $-0.01.

Steps to reproduce:  
From the initial state, do
`edit 1 -$9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: theodoreleebrant/ped#6

### LINKED ISSUE #124: [PE-D] I can top up by spending enough!
`add -d BUDGETBOOST -$1029384510928123` will cause me to get more money :D

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: theodoreleebrant/ped#13

### LINKED ISSUE #131: [PE-D] Sorting is case sensitive
Sorting by description is case sensitive in that `a` is after `Z`. Not sure if intended behavior, just letting y'all know.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: WangZijun97/ped#4

### LINKED ISSUE #133: [PE-D] Very large amounts seem to result in overflow
Running an `add` with `-$1234567890` resulted in what appears to be overflow. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: WangZijun97/ped#6

### PR DESCRIPTION
**Pull request by maxxyh**
Let's change how we use Amount throughout our code, using Amount for representation of monetary value instead of Double.

Also change `DescriptionComparator` to use case-insensitive alphabetical sorting. Fixes #131

Change Amount datatype to BigDecimal
Add wrapper methods for arithmetic operations on Amount
Fixed Equality comparators of Amount
Change Statistics.java Interface and BudgetDisplay.java to use Amount

Fixes #133, fixes #124, fixes #117,

### CODE REVIEW

File: src/main/java/seedu/expense/model/expense/Amount.java [hunk 1]
```diff
@@ -3,30 +3,38 @@
...
-
+public class Amount implements Comparable<Amount> {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Expense amount should only contain numbers and 1 '.', and should be in the {dollars}.{cents} format."
-                    + "{.cents} is optional but {dollars} should contain at least 1 digit.";
+            "Expense Amount restrictions:\n"
+            + "Amount Format: should only contain numbers and 1 '.', and should be in the <dollars>.<cents> format.\n"
+            + "    \".<cents>\" input is optional but <dollars> should contain at least 1 digit.\n"
+            + "Value Restrictions: -10e9 to 10e9 inclusive";
```
Comment (Jaylenlee) [inline src/main/java/seedu/expense/model/expense/Amount.java]: Value restriction should be 0 to 10e9 since amount cannot be negative

Comment (maxxyh) [reply src/main/java/seedu/expense/model/expense/Amount.java]: yup done!

**Comment by Jaylenlee** [comment]
LGTM
