### PR TITLE
Fix bug which allowed invalid dates

### LINKED ISSUE #122: [PE-D] Invalid dates does not parse correctly
Step to reproduce: `add -d dinnerasdf -$10.50 -@29-02-2021 t/Food`

(Entry 13 below shows 28-02-2021)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: theodoreleebrant/ped#11

### PR DESCRIPTION
**Pull request by Jaylenlee**
Bug Fix for #122

### CODE REVIEW

File: src/main/java/seedu/expense/model/expense/Date.java [hunk 1]
```diff
@@ -49,8 +49,13 @@ public Date() {
     public static boolean isValidDate(String test) {
         if (test.matches(VALIDATION_REGEX)) {
             try {
-                LocalDate.parse(test, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
-                return true;
+                LocalDate date = LocalDate.parse(test, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
+                // yyyy-MM-dd
+                String reformattedTest = test.substring(6) + test.substring(2, 6) + test.substring(0, 2);
+                if (date.toString().equals(reformattedTest)) {
```
Comment (maxxyh) [inline src/main/java/seedu/expense/model/expense/Date.java]: GENIUS HAHAHA but I think perhaps using regex could be cleaner? Can also use the DateTimeFormatter to format the date into dd-MM-yyyy!

**Review by maxxyh — APPROVED** [review]
LGTM this is a smart fix!!

**Review by maxxyh — APPROVED** [review]
