### PR TITLE
Hide budget display

### LINKED ISSUE #98: Find Command budget display is not displaying overall budget balance
image

Bug: FindCommand is displaying the (Total Budget - Expenses on Screen), which doesn't seem to be right when considering the FindCommand 

Steps to reproduce: 
1. Have a list larger than expenses to be found 
2. Execute FindCommand

### PR DESCRIPTION
**Pull request by Jaylenlee**
Fixes #98

### CODE REVIEW

File: src/main/java/seedu/expense/ui/MainWindow.java [hunk 1]
```diff
@@ -195,6 +195,12 @@ private CommandResult executeCommand(String commandText) throws CommandException
                 handleExit();
             }
 
+            if (!commandResult.isShowBudgetDisplay() || (commandResult.isShowHelp() && !budgetDisplay.isVisible())) {
```
Comment (maxxyh) [inline src/main/java/seedu/expense/ui/MainWindow.java:198]: Don't really understand the need for the second part: 
` (commandResult.isShowHelp() && !budgetDisplay.isVisible())`

**Review by maxxyh — APPROVED** [review]
LGTM
